config:
  # externalNodeHost: "" # This overrides dscpNode.enabled when setting the API_HOST envar
  port: 80
  logLevel: info
  dbName: dscp
  dbPort: 5432
  # dev wallet address
  selfAddress: 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty
  auth:
    type: NONE
    jwksUri: https://dscp.eu.auth0.com/.well-known/jwks.json
    audience: dscp-test
    issuer: https://dscp.eu.auth0.com/

deployment:
  annotations: {}
  livenessProbe:
    enabled: true
  replicaCount: 1

ingress:
  annotations: {}
  # className
  enabled: true
  paths:
    - /v1/members

service:
  annotations: {}
  enabled: true
  port: 80

image:
  repository: ghcr.io/digicatapult/dscp-identity-service
  pullPolicy: IfNotPresent
  tag: 'v1.5.0'
  pullSecrets: ['ghcr-digicatapult']

postgresql:
  enabled: true
  postgresqlDatabase: dscp
  postgresqlUsername: postgres
  postgresqlPassword: postgres
dscpNode:
  enabled: true
