apiVersion: v2
name: vitalam-identity-service
appVersion: '0.0.5'
description: A Helm chart for vitalam-identity-service
version: '0.0.5'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
dependencies:
  - name: postgresql
    version: '^10.12.2'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: vitalam-node
    version: '0.23.6'
    repository: https://digicatapult.github.io/vitalam-node/
    condition: vitalamNode.enabled
    alias: vitalamNode
